# 应用程序配置文件
# YAML (YAML Ain't Markup Language) 是一种人类可读的数据序列化标准

# 服务器配置
server:
  # 服务器监听端口
  port: 3000

  # 服务器绑定主机
  host: localhost

  # 是否启用 HTTPS
  https: false

# 数据库配置
database:
  # 数据库类型
  type: mysql

  # 数据库连接信息
  connection:
    host: localhost
    port: 3306
    username: myuser
    password: mypassword
    database: myapp

  # 连接池配置
  pool:
    min: 5
    max: 20
    acquire: 60000
    idle: 10000

# 日志配置
logging:
  # 日志级别 (error, warn, info, debug)
  level: info

  # 日志文件路径
  file: ./logs/app.log

  # 是否输出到控制台
  console: true

# 功能开关
features:
  # 用户认证功能
  authentication: true

  # 缓存功能
  caching: true

  # 监控功能
  monitoring: false

# 应用程序设置
app:
  # 应用名称
  name: MyApp

  # 应用版本
  version: 1.0.0

  # 支持的语言列表
  languages:
    - zh
    - en

  # 默认语言
  defaultLanguage: zh
